name: gql_websocket_link
version: 2.0.0
description: GQL Websocket Link
repository: https://github.com/gql-dart/gql
environment:
  sdk: ">=2.15.0 <4.0.0"
dependencies:
  gql: ^1.0.0+1
  gql_exec: ^1.0.0+1
  gql_link: ^1.0.0+1
  meta: ^1.10.0
  rxdart: ">=0.26.0 <0.28.0"
  uuid: ^4.2.1
  web_socket_channel: ^2.4.0
dev_dependencies:
  gql_pedantic: ^1.1.0
  mockito: ^5.4.3
  test: ^1.24.9
topics:
  - graphql
  - gql
  - gql-link
